spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  #    timeout: 10000
  cache:
    redis:
      cache-null-values: false
      key-prefix: student
      use-key-prefix: true
      time-to-live: 60000